### PR TITLE
[UG] update Ker Wei

### LINKED ISSUE #160: [PE-D] Confusing points in UserGuide for add-c
Unsure what the points in red curly braces mean. perhaps they are points left from find command?

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: ongch00/ped#3

### LINKED ISSUE #192: [PE-D] Format/unit for weight and height
The app allows adding weights and heights of clients, but the documentation doesn't specify the unit for the same, which can be confusing for the user. 

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: raivatshah/ped#9

### LINKED ISSUE #199: [PE-D] Gender Format not given in User guide
When creating a client profile using `add-c`, the command only allows ` genders `Male/Female/Others`. However, this is not seen in the UG. 

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: raivatshah/ped#2

### PR DESCRIPTION
**Pull request by charrizard47**

### CODE REVIEW

**Comment by charrizard47** [comment]
PR fixes #160 #190 #192

**Review by AaronCQL — DISMISSED** [review]
LGTM

**Comment by AaronCQL** [comment]
Please solve the conflicts!

**Review by AaronCQL — APPROVED** [review]
LGTM

**Pull request merged**
